language: rust
rust:
    - nightly

services:
    - docker

before_install:
    - docker pull scssubstratee/substratee_dev:18.04-2.9.1-1.1.2
    - docker run -d scssubstratee/substratee_dev:18.04-2.9.1-1.1.2 /bin/sh -c "ls -la"
    - docker ps -a
