language: rust

services:
    - docker

before_install:
    - docker pull scssubstratee/substratee_dev:18.04-2.9.1-1.1.2

install:
    - docker run --rm scssubstratee/substratee_dev:18.04-2.9.1-1.1.2 /bin/bash -c "ls -la"

before_script:
    - readlink -f .travis.yml

script:
    - docker run --rm scssubstratee/substratee_dev:18.04-2.9.1-1.1.2 /bin/bash -c "rustup show"