language: rust

cache: cargo

services:
    - docker

before_install:
    - docker pull $DOCKER_IMAGE

install:
    - docker images

script:
    - docker run --rm
      -v /home/travis/build/electronix/encointer-node:/encointer-node
      $DOCKER_IMAGE
      /bin/bash -c "cd /encointer-node && cargo build --release"

env:
    global:
        - DOCKER_IMAGE: scssubstratee/substratee_dev:18.04-2.9.1-1.1.2